### ISSUE TITLE
No CSS injection

### ISSUE THREAD

**Issue by elithecodemaker** [Thomas101/wmail#642]
* Which version of WMail are you using? [e.g. 1.3.1]
11104
* Which Operating System are you using? [e.g. Windows 10, Mac OSX 10, Ubuntu 14.04]
Windows 10

CSS injection failing. Seeing only original inbox style for all accounts on new install.

**Comment by Thomas101** [comment]
Hi, what CSS are you trying to add? If you do something drastic like...

```css
* {
background-color: red !important;
color: yellow !important;
}
```

... does that work?
